// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "f267f347-53e8-4c5f-8263-2cee1f80fda9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFlameStrengthChange();
void onFurnaceChange();

CloudElectricPotential flameStrength;
CloudTemperatureSensor furnace;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(flameStrength, READWRITE, 10 * SECONDS, onFlameStrengthChange);
  ArduinoCloud.addProperty(furnace, READWRITE, 10 * SECONDS, onFurnaceChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
