esphome:
  name: lonely-binary-number-one
  friendly_name: Lonely binary number one.

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "avRCBNjKrhlYicjnNGHDsPKzgwc5UXP8pVtV1+yV2MU="

ota:
  - platform: esphome
    password: "cb9e7c0da1c8db2d0ac3953c36170239"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lonely-Binary-Number-One"
    password: "vfAgYUE0sD2D"

captive_portal:
    