esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WyEYTttk/RGS1Az8xvWYKeedslqvftw5IikX7F7MADg="

ota:
  - platform: esphome
    password: "266088c9c62a95480b3ce820f7dd9ccd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "j67WApej27lL"

captive_portal:
    